### ISSUE TITLE
Regex patterns are really glob patterns

### ISSUE THREAD

**Issue by rgov** [OceanDataTools/openvdm#50]
There are several places in config files or scripts where "regex" is mentioned like these:

> These filters use the standard regex structure language (i.e. *.Raw).

> `"regex":"NAV/CNAV-GGA_*.json"`

These are [glob patterns](https://en.wikipedia.org/wiki/Glob_%28programming%29) which are (outside of theory) not the same as regular expressions. In the code they are matched with [`fnmatch.fnmatch()`](https://docs.python.org/3/library/fnmatch.html) rather than `re.match()`.

**Comment by webbpinner** [comment]
I've updated the help text to say this is glob querying vs regex in the dev branch of the code.  Will appear in the master branch at the next release.  I'm leaving the under-the-hood code as regex as I think I'm going to migrate the code to use regex in a future release.
